name: flutter_fillbars
description: flutter_fillbars is a simple flutter package that allows you to create a container which fills animatedly.
version: 1.1.0
homepage: https://github.com/SirioRigel/flutter_fillbars

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

funding:
  - https://www.buymeacoffee.com/tommasomiliani

topics:
  - ui
  - functionalities