name: flutter_fillbars
description: flutter_fillbars is a simple flutter package that allows you to create a container which can fill with or without an animation. Play with the shape of the container to make it more elliptical, or use the preset to make it fully circular. You can apply a static color to it or use a list of color and a Gradient will be created and applied to your Fillbar. 
version: 1.3.0
homepage: https://github.com/SirioRigel/flutter_fillbars

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

funding:
  - https://www.buymeacoffee.com/tommasomiliani

topics:
  - ui
  - functionalities